import { AGENT_RUN_PHASES, AGENT_TASK_TYPES, LIMITS } from '@antigv/shared';
import { generateTaskResponse } from '../llm/llmRouter.js';
import { editJsonSchemaInstructions } from './schemas/editSchema.js';
import { runCritic } from './criticAgent.js';
import { runFixer } from './fixerAgent.js';
import { validatePatchPayload } from './preflightValidator.js';
import { renderContextBundle } from './contextBundleBuilder.js';
import { readFile, exists, getWorkspaceRoot } from '../fs/fileService.js';
import { activeShadowWorkspace } from './shadowWorkspace.js';
import { runIncrementalVerification } from './verificationAgent.js';
import { activePatternDetector } from './failurePatternDetector.js';
import { recordRepairMetric } from '../llm/telemetryService.js';
import path from 'path';

const CODER_SYSTEM_PROMPT = `
You are an expert Software Engineer Coder Agent.
You are given a canonical task brief, a focused context slice, and a single plan step.
Return valid JSON only using minimal search/replace edits.

CRITICAL RULES:
1. Search text must be copied verbatim from the supplied file content.
2. Keep patches minimal and localized.
3. Never rewrite the whole file unless the file is new.
4. Use the schema exactly.
5. For NEW files (action = CREATE), write the complete file content as one REPLACE block with an empty search string.
6. If the step says CREATE but the file already exists (e.g. generated by a scaffolding tool), treat it as a MODIFY — use targeted search/replace to customize the existing content.
7. For framework projects (React, Next.js, Vite, etc.), DO NOT generate boilerplate config files — the CLI scaffold already created them. Only modify what the user specifically requested.

SCHEMA:
${editJsonSchemaInstructions}
`;

function addLineNumbers(content) {
  return content
    .split('\n')
    .map((line, i) => `${String(i + 1).padStart(4, ' ')}: ${line}`)
    .join('\n');
}

// Applies edits to block of text, identical to diffService apply patch
// We need this locally to stage the simulated file in the shadow workspace
function simulatePatchApplication(originalContent, edits) {
  let result = originalContent;
  for (const edit of edits) {
    if (!edit.search) {
      result = edit.replace; // New file logic
      continue;
    }
    if (result.includes(edit.search)) {
      result = result.replace(edit.search, edit.replace);
    } else {
      throw new Error(
        `Search block not found verbatim in file for this edit: ${edit.search.substring(0, 30)}...`
      );
    }
  }
  return result;
}

export async function generateCodeEdits(plan, contextBundle, taskBrief, socket, options = {}) {
  const edits = [];
  const isCancelled = options.isCancelled || (() => false);
  const runId = options.runId;

  // Reset shadow workspace and failure patterns for this execution run
  activeShadowWorkspace.clearAll();
  activePatternDetector.reset();

  for (const step of plan.steps || []) {
    if (isCancelled()) break;

    const files = step.files?.length ? step.files : [step.filePath].filter(Boolean);
    const primaryFile = files[0] || step.filePath;
    const fileGroupId = step.fileGroupId || `group-${step.stepId}`;

    // -- Handle RUN_COMMAND explicitly --
    if (step.action === 'RUN_COMMAND') {
      const commandToRun = step.command || step.description;
      socket.emit('agent:thinking', { message: `Executing command for step ${step.stepId}` });
      socket.emit('agent:run_state', {
        runId,
        phase: AGENT_RUN_PHASES.CODEGEN,
        taskType: AGENT_TASK_TYPES.STEP_CODEGEN,
        status: 'running',
        stepId: step.stepId,
        message: `Executing: ${commandToRun}`,
      });
      socket.emit('agent:step:start', {
        stepId: `code_${step.stepId}`,
        description: `Execute: ${commandToRun}`,
      });
      socket.emit('agent:terminal:run', { command: commandToRun });

      // Wait for the command to finish before continuing.
      // Scaffolding commands (npx create-*) can take 30+ seconds.
      const isScaffolding =
        /\b(create-next-app|create-vite|create-react-app|create-vue|create-svelte|angular\/cli|npm install|pnpm install|yarn install|npx)\b/i.test(
          commandToRun
        );
      const waitMs = isScaffolding ? 30000 : 5000;
      socket.emit('agent:thinking', {
        message: `Waiting for command to complete (up to ${waitMs / 1000}s)...`,
      });

      await new Promise((resolve) => {
        let output = '';
        const timeoutId = setTimeout(() => {
          socket.off('terminal:output', outputListener);
          resolve();
        }, waitMs);

        const outputListener = (payload) => {
          output += payload.data || '';
          // Detect shell prompt patterns that indicate the command has finished
          const lastLines = output.split('\n').slice(-3).join('\n');
          if (/[\$#>]\s*$/.test(lastLines) || /PS\s+[A-Z]:\\/.test(lastLines)) {
            clearTimeout(timeoutId);
            socket.off('terminal:output', outputListener);
            setTimeout(resolve, 500); // small grace period
          }
        };
        socket.on('terminal:output', outputListener);
      });

      socket.emit('agent:step:done', { stepId: `code_${step.stepId}` });
      continue;
    }

    socket.emit('agent:thinking', { message: `Writing code for step ${step.stepId}` });
    socket.emit('agent:run_state', {
      runId,
      phase: AGENT_RUN_PHASES.CODEGEN,
      taskType: AGENT_TASK_TYPES.STEP_CODEGEN,
      status: 'running',
      stepId: step.stepId,
      filePaths: files,
      message: `Codegen for step ${step.stepId}`,
    });
    socket.emit('agent:step:start', {
      stepId: `code_${step.stepId}`,
      description: `${step.action} ${primaryFile}`,
    });

    let actualFileContent = 'File not found or is new.';
    let effectiveFilePath = primaryFile;

    try {
      if (primaryFile) {
        effectiveFilePath = await normalizeWorkspacePath(primaryFile);
        // Fallback to shadow workspace first to pick up changes from earlier steps
        actualFileContent = await activeShadowWorkspace.getFileContent(effectiveFilePath);
        if (!actualFileContent && (await exists(effectiveFilePath))) {
          actualFileContent = await readFile(effectiveFilePath);
        }
      }
    } catch (error) {
      console.warn(`[CoderAgent] Could not read ${effectiveFilePath}:`, error.message);
    }

    const isExistingFile = !!actualFileContent && actualFileContent !== 'File not found or is new.';
    const focusedContext = renderContextBundle(contextBundle, [
      'workspaceFocus',
      'retrievedChunks',
      'symbolGraph',
      'dependencyGraph',
      'verificationEvidence',
    ]);

    const stepPrompt = `CANONICAL TASK BRIEF:\n${JSON.stringify(taskBrief, null, 2)}\n\nAPPROVED PLAN STEP:\n${JSON.stringify(step, null, 2)}\n\nFOCUSED CONTEXT:\n${focusedContext}\n\nPRIMARY FILE:\n${effectiveFilePath}\n\nCURRENT FILE CONTENT (with line numbers for reference only):\n\`\`\`\n${isExistingFile ? addLineNumbers(actualFileContent) : '(new file)'}\n\`\`\``;

    try {
      const { content, provider, model } = await generateTaskResponse(
        [
          { role: 'system', content: CODER_SYSTEM_PROMPT },
          { role: 'user', content: stepPrompt },
        ],
        { runId, taskType: AGENT_TASK_TYPES.STEP_CODEGEN, temperature: 0.1, jsonMode: true }
      );

      let editResult = JSON.parse(content);
      editResult.stepId = step.stepId;
      editResult.filePath = effectiveFilePath;
      editResult.fileGroupId = fileGroupId;
      editResult.files = files;
      editResult.verificationHints = step.verificationHints || [];
      editResult.retryCount = 0;

      let retryCount = 0;
      let feedback = '';
      let isCorrect = false;

      while (retryCount <= LIMITS.MAX_FIXER_RETRIES) {
        // 1. FAST PREFLIGHT
        const preflight = validatePatchPayload(editResult, isExistingFile ? actualFileContent : '');
        if (!preflight.valid) {
          feedback = `Preflight structural error: ${preflight.issues.join(' ')}`;
          isCorrect = false;
        } else {
          // 2. CRITIC CONSENSUS (LLM)
          const criticResult = await runCritic({
            runId,
            prompt: step.description,
            fileContent: actualFileContent,
            filePath: effectiveFilePath,
            proposedEdits: editResult.edits || [],
          });

          isCorrect = criticResult.isCorrect;
          feedback = criticResult.feedback || '';

          if (isCorrect) {
            // 3. STAGE IN SHADOW WORKSPACE
            try {
              const patchedContent = simulatePatchApplication(
                isExistingFile ? actualFileContent : '',
                editResult.edits
              );
              const deps = step.depends_on || step.dependsOn || [];
              await activeShadowWorkspace.stagePatch(
                fileGroupId,
                effectiveFilePath,
                patchedContent,
                deps
              );

              // 4. INCREMENTAL VERIFICATION (Syntax Native Check)
              socket.emit('agent:thinking', {
                message: `Verifying syntax for step ${step.stepId}`,
              });
              const vResult = await runIncrementalVerification(fileGroupId, { runId });

              if (!vResult.verified) {
                isCorrect = false;
                feedback = `Verification Failed after patching: ${vResult.issues.map((i) => i.message).join(' | ')}`;
                activeShadowWorkspace.clearGroup(fileGroupId); // Revert shadow staging on fail
              }
            } catch (err) {
              isCorrect = false;
              feedback = `Patch Application Failed: ${err.message}`;
            }
          }
        }

        if (isCorrect) break;

        retryCount += 1;
        if (retryCount > LIMITS.MAX_FIXER_RETRIES) break;

        // Run the robust Fixer Loop with Failure Pattern Detection (Model Rotation built-in)
        socket.emit('agent:thinking', {
          message: `Fixing patch for step ${step.stepId} (Attempt ${retryCount})`,
        });
        const fixedEdits = await runFixer({
          runId,
          stepId: step.stepId,
          fileGroupId,
          prompt: step.description,
          fileContent: actualFileContent,
          filePath: effectiveFilePath,
          previousEdits: editResult.edits || [],
          errorFeedback: feedback,
        });

        editResult = { ...editResult, edits: fixedEdits, retryCount };
      }

      recordRepairMetric(runId, model, editResult.retryCount || 0);

      edits.push(editResult);

      socket.emit('agent:step:code', {
        stepId: `code_${step.stepId}`,
        chunk: JSON.stringify(editResult, null, 2),
        provider,
        model,
        criticFeedback: feedback || 'Approved and verified on first pass.',
        file: effectiveFilePath,
        files,
        fileGroupId: editResult.fileGroupId,
        verificationHints: editResult.verificationHints,
        repairTelemetry: {
          retryCount: editResult.retryCount || 0,
          modelUsed: model,
          rotations: editResult.retryCount > 0 ? editResult.retryCount : 0,
        },
        conflicts: activeShadowWorkspace.hasConflicts(fileGroupId)
          ? activeShadowWorkspace.getConflicts().filter((c) => c.groups.includes(fileGroupId))
          : [],
      });
    } catch (error) {
      console.error(`[CoderAgent] Failed on step ${step.stepId}:`, error.message);
      socket.emit('agent:error', {
        message: `Coder failed on step ${step.stepId}: ${error.message}`,
      });
    }

    socket.emit('agent:step:done', { stepId: `code_${step.stepId}` });
  }

  return edits;
}

export async function normalizeWorkspacePath(filePath) {
  if (!filePath) return '/';
  let normalized = filePath.replace(/\\/g, '/').trim();
  if (!normalized.startsWith('/')) normalized = '/' + normalized;

  const workspaceRoot = getWorkspaceRoot();
  const rootName = path.basename(workspaceRoot);
  const absoluteRoot = path.resolve(workspaceRoot);
  const absoluteFilePath = path.resolve(filePath);

  if (absoluteFilePath.toLowerCase().startsWith(absoluteRoot.toLowerCase())) {
    const relative = path.relative(absoluteRoot, absoluteFilePath);
    return '/' + relative.replace(/\\/g, '/');
  }

  const segments = normalized.split('/').filter(Boolean);
  if (segments[0]?.toLowerCase() === rootName.toLowerCase()) {
    return '/' + segments.slice(1).join('/');
  }
  return normalized;
}
