import { AGENT_TASK_TYPES } from '@antigv/shared';
import { generateTaskResponse } from '../llm/llmRouter.js';
import { editJsonSchemaInstructions } from './schemas/editSchema.js';
import { activePatternDetector } from './failurePatternDetector.js';

const fixerSystemPrompt = `
You are an expert Software Engineer FIXER Agent.
The previous code generation produced incorrect edits. Fix them and return valid JSON only.

RULES:
1. The "search" text must exist verbatim in the supplied file content.
2. Keep the patch minimal and focused.
3. For create-file steps, use an empty search string and full file content in replace.

SCHEMA:
${editJsonSchemaInstructions}
`;

export async function runFixer(params) {
  const { prompt, fileContent, filePath, previousEdits, errorFeedback, runId, stepId, fileGroupId } = params;

  // 1. Evaluate the failure pattern
  const evaluation = activePatternDetector.evaluateFailure(
    stepId || 'unknown_step', 
    fileGroupId || 'unknown_group', 
    errorFeedback
  );

  console.warn(`[FixerAgent] Pattern evaluation: ${evaluation.action}. Message: ${evaluation.message}`);

  if (evaluation.action === 'escalate_to_user') {
    throw new Error(`Unrecoverable failure cycle detected: ${evaluation.message}\nLast error: ${errorFeedback}`);
  }

  // 2. Determine router overrides based on pattern evaluation
  const routeOverrides = {};
  let feedbackToSend = errorFeedback;
  
  if (evaluation.action === 'switch_model') {
    routeOverrides.forceFallback = true;
    feedbackToSend = `${errorFeedback}\n\n[CRITICAL NOTE TO NEW MODEL]: The previous model repeatedly failed with this error. You must try a fundamentally different approach to fixing it.`;
  }

  try {
    const { content, model } = await generateTaskResponse(
      [
        { role: 'system', content: fixerSystemPrompt },
        {
          role: 'user',
          content: `<User Request>\n${prompt}\n</User Request>\n\n<File Path>\n${filePath}\n</File Path>\n\n<Current File Content>\n\`\`\`\n${fileContent}\n\`\`\`\n</Current File Content>\n\n<Your Previous Attempt>\n\`\`\`json\n${JSON.stringify({ edits: previousEdits }, null, 2)}\n\`\`\`\n</Your Previous Attempt>\n\n<Error / Critic Feedback>\n${feedbackToSend}\n</Error / Critic Feedback>`,
        },
      ],
      {
        runId,
        taskType: AGENT_TASK_TYPES.FIX_GENERATION,
        jsonMode: true,
        routeOverrides
      }
    );

    console.log(`[FixerAgent] Fix generated by model: ${model}`);
    return JSON.parse(content).edits || [];
  } catch (error) {
    console.error('[FixerAgent] Failed to fix edit:', error);
    return [];
  }
}
