import {
  AGENT_TASK_TYPES,
  DEFAULT_ROUTE_WEIGHTS,
  LIMITS,
  PROVIDER_AVAILABILITY,
} from '@antigv/shared';

export const MODEL_REGISTRY = [
  {
    provider: 'groq',
    modelId: 'llama-3.3-70b-versatile',
    taskFit: [
      AGENT_TASK_TYPES.INTENT_CLASSIFICATION,
      AGENT_TASK_TYPES.TASK_BRIEF,
      AGENT_TASK_TYPES.PLANNING,
      AGENT_TASK_TYPES.PATCH_REVIEW,
      AGENT_TASK_TYPES.FIX_GENERATION,
      AGENT_TASK_TYPES.CHAT_ANSWER,
    ],
    contextWindow: 128000,
    maxOutputTokens: 4096,
    jsonModeSupport: true,
    toolUseSupport: false,
    streamingSupport: true,
    specialCapabilities: ['json_schema', 'fast_reasoning'],
    costTier: 0,
    latencyP95: 1200,
    errorRate: 0.02,
    availabilityState: PROVIDER_AVAILABILITY.HEALTHY,
    deprecationDate: null,
    fallbackPriority: 1,
  },
  {
    provider: 'groq',
    modelId: 'qwen-qwq-32b',
    taskFit: [AGENT_TASK_TYPES.PLANNING, AGENT_TASK_TYPES.STEP_CODEGEN],
    contextWindow: 32000,
    maxOutputTokens: 4096,
    jsonModeSupport: true,
    toolUseSupport: false,
    streamingSupport: true,
    specialCapabilities: ['reasoning', 'code'],
    costTier: 0,
    latencyP95: 1500,
    errorRate: 0.03,
    availabilityState: PROVIDER_AVAILABILITY.HEALTHY,
    deprecationDate: null,
    fallbackPriority: 2,
  },
  {
    provider: 'nvidia',
    modelId: 'meta/llama-3.3-70b-instruct',
    taskFit: [
      AGENT_TASK_TYPES.PLANNING,
      AGENT_TASK_TYPES.STEP_CODEGEN,
      AGENT_TASK_TYPES.PATCH_REVIEW,
    ],
    contextWindow: 128000,
    maxOutputTokens: 4096,
    jsonModeSupport: true,
    toolUseSupport: false,
    streamingSupport: true,
    specialCapabilities: ['code', 'reasoning'],
    costTier: 0,
    latencyP95: 2200,
    errorRate: 0.04,
    availabilityState: PROVIDER_AVAILABILITY.UNKNOWN,
    deprecationDate: null,
    fallbackPriority: 3,
  },
  {
    provider: 'nvidia',
    modelId: 'ibm/granite-34b-code-instruct',
    taskFit: [AGENT_TASK_TYPES.STEP_CODEGEN, AGENT_TASK_TYPES.FIX_GENERATION],
    contextWindow: 32000,
    maxOutputTokens: 4096,
    jsonModeSupport: true,
    toolUseSupport: false,
    streamingSupport: true,
    specialCapabilities: ['code'],
    costTier: 0,
    latencyP95: 2400,
    errorRate: 0.04,
    availabilityState: PROVIDER_AVAILABILITY.UNKNOWN,
    deprecationDate: null,
    fallbackPriority: 4,
  },
  {
    provider: 'openrouter',
    modelId: 'openai/gpt-oss-20b:free',
    taskFit: [
      AGENT_TASK_TYPES.TASK_BRIEF,
      AGENT_TASK_TYPES.INTENT_CLASSIFICATION,
      AGENT_TASK_TYPES.PLANNING,
      AGENT_TASK_TYPES.STEP_CODEGEN,
      AGENT_TASK_TYPES.CHAT_ANSWER,
    ],
    contextWindow: 128000,
    maxOutputTokens: 4096,
    jsonModeSupport: true,
    toolUseSupport: false,
    streamingSupport: true,
    specialCapabilities: ['brokered_free_tier'],
    costTier: 0,
    latencyP95: 2600,
    errorRate: 0.08,
    availabilityState: PROVIDER_AVAILABILITY.UNKNOWN,
    deprecationDate: null,
    fallbackPriority: 5,
  },
  {
    provider: 'github',
    modelId: 'gpt-4.1-mini',
    taskFit: [AGENT_TASK_TYPES.PATCH_REVIEW, AGENT_TASK_TYPES.VERIFICATION_SUMMARY],
    contextWindow: 128000,
    maxOutputTokens: 4096,
    jsonModeSupport: true,
    toolUseSupport: false,
    streamingSupport: false,
    specialCapabilities: ['evaluation'],
    costTier: 1,
    latencyP95: 1800,
    errorRate: 0.02,
    availabilityState: PROVIDER_AVAILABILITY.UNKNOWN,
    deprecationDate: null,
    fallbackPriority: 6,
  },
];

export const TASK_ROUTE_CONFIG = {
  [AGENT_TASK_TYPES.INTENT_CLASSIFICATION]: {
    taskType: AGENT_TASK_TYPES.INTENT_CLASSIFICATION,
    preferredModels: ['llama-3.3-70b-versatile', 'openai/gpt-oss-20b:free'],
    scoreWeights: { ...DEFAULT_ROUTE_WEIGHTS, latency: 0.3, taskFit: 0.35 },
    maxInputTokens: LIMITS.MAX_TOKENS_PER_REQUEST,
    maxOutputTokens: 700,
    timeoutMs: 12000,
    temperature: 0.1,
    jsonMode: true,
    stream: false,
    toolUse: false,
    circuitBreakerPolicy: 'standard',
  },
  [AGENT_TASK_TYPES.TASK_BRIEF]: {
    taskType: AGENT_TASK_TYPES.TASK_BRIEF,
    preferredModels: ['llama-3.3-70b-versatile', 'openai/gpt-oss-20b:free'],
    scoreWeights: DEFAULT_ROUTE_WEIGHTS,
    maxInputTokens: LIMITS.MAX_TOKENS_PER_REQUEST,
    maxOutputTokens: 900,
    timeoutMs: 15000,
    temperature: 0.1,
    jsonMode: true,
    stream: false,
    toolUse: false,
    circuitBreakerPolicy: 'standard',
  },
  [AGENT_TASK_TYPES.PLANNING]: {
    taskType: AGENT_TASK_TYPES.PLANNING,
    preferredModels: ['llama-3.3-70b-versatile', 'meta/llama-3.3-70b-instruct', 'qwen-qwq-32b'],
    scoreWeights: { ...DEFAULT_ROUTE_WEIGHTS, taskFit: 0.5, latency: 0.1 },
    maxInputTokens: LIMITS.MAX_TOKENS_PER_REQUEST,
    maxOutputTokens: 1800,
    timeoutMs: 25000,
    temperature: 0.1,
    jsonMode: true,
    stream: false,
    toolUse: false,
    circuitBreakerPolicy: 'standard',
  },
  [AGENT_TASK_TYPES.STEP_CODEGEN]: {
    taskType: AGENT_TASK_TYPES.STEP_CODEGEN,
    preferredModels: [
      'qwen-qwq-32b',
      'ibm/granite-34b-code-instruct',
      'meta/llama-3.3-70b-instruct',
    ],
    scoreWeights: { ...DEFAULT_ROUTE_WEIGHTS, taskFit: 0.5, latency: 0.1 },
    maxInputTokens: LIMITS.MAX_TOKENS_PER_REQUEST,
    maxOutputTokens: 2400,
    timeoutMs: 30000,
    temperature: 0.1,
    jsonMode: true,
    stream: false,
    toolUse: false,
    circuitBreakerPolicy: 'standard',
  },
  [AGENT_TASK_TYPES.PATCH_REVIEW]: {
    taskType: AGENT_TASK_TYPES.PATCH_REVIEW,
    preferredModels: ['llama-3.3-70b-versatile', 'gpt-4.1-mini'],
    scoreWeights: DEFAULT_ROUTE_WEIGHTS,
    maxInputTokens: LIMITS.MAX_TOKENS_PER_REQUEST,
    maxOutputTokens: 1200,
    timeoutMs: 15000,
    temperature: 0,
    jsonMode: true,
    stream: false,
    toolUse: false,
    circuitBreakerPolicy: 'standard',
  },
  [AGENT_TASK_TYPES.FIX_GENERATION]: {
    taskType: AGENT_TASK_TYPES.FIX_GENERATION,
    preferredModels: ['ibm/granite-34b-code-instruct', 'llama-3.3-70b-versatile'],
    scoreWeights: { ...DEFAULT_ROUTE_WEIGHTS, taskFit: 0.5 },
    maxInputTokens: LIMITS.MAX_TOKENS_PER_REQUEST,
    maxOutputTokens: 2000,
    timeoutMs: 20000,
    temperature: 0.05,
    jsonMode: true,
    stream: false,
    toolUse: false,
    circuitBreakerPolicy: 'standard',
  },
  [AGENT_TASK_TYPES.CHAT_ANSWER]: {
    taskType: AGENT_TASK_TYPES.CHAT_ANSWER,
    preferredModels: ['llama-3.3-70b-versatile', 'openai/gpt-oss-20b:free'],
    scoreWeights: { ...DEFAULT_ROUTE_WEIGHTS, latency: 0.3, taskFit: 0.35 },
    maxInputTokens: LIMITS.MAX_TOKENS_PER_REQUEST,
    maxOutputTokens: 1600,
    timeoutMs: 20000,
    temperature: 0.2,
    jsonMode: false,
    stream: true,
    toolUse: false,
    circuitBreakerPolicy: 'standard',
  },
  [AGENT_TASK_TYPES.VERIFICATION_SUMMARY]: {
    taskType: AGENT_TASK_TYPES.VERIFICATION_SUMMARY,
    preferredModels: ['gpt-4.1-mini', 'llama-3.3-70b-versatile'],
    scoreWeights: DEFAULT_ROUTE_WEIGHTS,
    maxInputTokens: LIMITS.MAX_TOKENS_PER_REQUEST,
    maxOutputTokens: 1000,
    timeoutMs: 15000,
    temperature: 0.1,
    jsonMode: false,
    stream: false,
    toolUse: false,
    circuitBreakerPolicy: 'standard',
  },
};

export function getTaskRouteConfig(taskType) {
  return (
    TASK_ROUTE_CONFIG[taskType] || {
      taskType,
      preferredModels: MODEL_REGISTRY.map((m) => m.modelId),
      scoreWeights: DEFAULT_ROUTE_WEIGHTS,
      maxInputTokens: LIMITS.MAX_TOKENS_PER_REQUEST,
      maxOutputTokens: 1200,
      timeoutMs: 15000,
      temperature: 0.2,
      jsonMode: false,
      stream: false,
      toolUse: false,
      circuitBreakerPolicy: 'standard',
    }
  );
}
